sudo: required

services:
  - docker

before_install:
  - docker build -t testing:latest .
  - docker network create testing
  - docker run -d --network testing -p 81:80 --name helloworld tutum/hello-world
  - docker run --network testing --name testing -d -p 80:80 -e VARNISH_BACKEND_ADDRESS=helloworld -e VARNISH_BACKEND_PORT=80 testing:latest

# TODO: add a real testdd
script:
  - docker ps -a
  - sleep 5
  - test $(wget -qO- http://127.0.0.1/ | wc -l) -gt 0
  - sleep 10
  - test $(wget -qO- http://127.0.0.1/ | wc -l) -gt 0
  - docker logs testing
  - test $(docker logs testing | grep MISS | wc -l) -eq 1 && test $(docker logs testing | grep HIT | wc -l) -eq 1
  - ./version.sh

after_script:
  - docker stop testing helloworld && docker rm testing helloworld && docker network rm testing
